[package]
name = "raytracer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.7.0"
image = "^0.24.2"
indicatif = "^0.16.2"
num-traits = "^0.2.15"
rand = "^0.8.5"
dotenv = "0.15.0"